package edu.costavitor.setanotificationapi.notifications;

import java.util.HashMap;
import java.util.Map;

public class NotificationDBFMappings {

    public static final Map<String, String> NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD = new HashMap<>();

    private static final String NU_NOTIFIC = "NU_NOTIFIC";
    private static final String TP_NOT = "TP_NOT";
    private static final String ID_AGRAVO = "ID_AGRAVO";
    private static final String DT_NOTIFIC = "DT_NOTIFIC";
    private static final String SEM_NOT = "SEM_NOT";
    private static final String SG_UF_NOT = "SG_UF_NOT";
    private static final String ID_MUNICIP = "ID_MUNICIP";
    private static final String ID_UNIDADE = "ID_UNIDADE";
    private static final String DT_SIN_PRI = "DT_SIN_PRI";
    private static final String SEM_PRI = "SEM_PRI";
    private static final String NM_PACIENT = "NM_PACIENT";
    private static final String DT_NASC = "DT_NASC";
    private static final String NU_IDADE_N = "NU_IDADE_N";
    private static final String CS_SEXO = "CS_SEXO";
    private static final String CS_GESTANT = "CS_GESTANT";
    private static final String CS_RACA = "CS_RACA";
    private static final String CS_ESCOL_N = "CS_ESCOL_N";
    private static final String ID_CNS_SUS = "ID_CNS_SUS";
    private static final String NM_MAE_PAC = "NM_MAE_PAC";
    private static final String SG_UF = "SG_UF";
    private static final String ID_MN_RESI = "ID_MN_RESI";
    private static final String ID_DISTRIT = "ID_DISTRIT";
    private static final String ID_BAIRRO = "ID_BAIRRO";
    private static final String NM_BAIRRO = "NM_BAIRRO";
    private static final String ID_LOGRADO = "ID_LOGRADO";
    private static final String NM_LOGRADO = "NM_LOGRADO";
    private static final String NU_NUMERO = "NU_NUMERO";
    private static final String NM_COMPLEM = "NM_COMPLEM";
    private static final String NU_CEP = "NU_CEP";
    private static final String NU_DDD_TEL = "NU_DDD_TEL";
    private static final String NU_TELEFON = "NU_TELEFON";
    private static final String CS_ZONA = "CS_ZONA";
    private static final String ID_PAIS = "ID_PAIS";
    private static final String DT_INVEST = "DT_INVEST";
    private static final String FEBRE = "FEBRE";
    private static final String MIALGIA = "MIALGIA";
    private static final String CEFALEIA = "CEFALEIA";
    private static final String EXANTEMA = "EXANTEMA";
    private static final String VOMITO = "VOMITO";
    private static final String NAUSEA = "NAUSEA";
    private static final String DOR_COSTAS = "DOR_COSTAS";
    private static final String CONJUNTVIT = "CONJUNTVIT";
    private static final String ARTRITE = "ARTRITE";
    private static final String ARTRALGIA = "ARTRALGIA";
    private static final String PETEQUIA_N = "PETEQUIA_N";
    private static final String LEUCOPENIA = "LEUCOPENIA";
    private static final String LACO = "LACO";
    private static final String DOR_RETRO = "DOR_RETRO";
    private static final String DIABETES = "DIABETES";
    private static final String HEMATOLOG = "HEMATOLOG";
    private static final String HEPATOPAT = "HEPATOPAT";
    private static final String RENAL = "RENAL";
    private static final String HIPERTENSA = "HIPERTENSA";
    private static final String ACIDO_PEPT = "ACIDO_PEPT";
    private static final String AUTO_IMUNE = "AUTO_IMUNE";
    private static final String DT_SORO = "DT_SORO";
    private static final String RESUL_SORO = "RESUL_SORO";
    private static final String DT_NS1 = "DT_NS1";
    private static final String RESUL_NS1 = "RESUL_NS1";
    private static final String DT_VIRAL = "DT_VIRAL";
    private static final String RESUL_VI_N = "RESUL_VI_N";
    private static final String DT_PCR = "DT_PCR";
    private static final String RESUL_PCR_ = "RESUL_PCR_";
    private static final String SOROTIPO = "SOROTIPO";
    private static final String CLASSI_FIN = "CLASSI_FIN";
    private static final String CRITERIO = "CRITERIO";
    private static final String EVOLUCAO = "EVOLUCAO";
    private static final String DT_OBITO = "DT_OBITO";
    private static final String DT_ENCERRA = "DT_ENCERRA";
    private static final String DS_OBS = "DS_OBS";

    static {
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NU_NOTIFIC, NotificationEntity.Fields.nuNotificacao);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(TP_NOT, NotificationEntity.Fields.tpNotificacao);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ID_AGRAVO, NotificationEntity.Fields.coCid);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DT_NOTIFIC, NotificationEntity.Fields.dtNotificacao);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(SEM_NOT, NotificationEntity.Fields.dsSemanaNotificacao);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(SG_UF_NOT, NotificationEntity.Fields.coUfNotificacao);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ID_MUNICIP, NotificationEntity.Fields.coMunicipioNotificacao);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ID_UNIDADE, NotificationEntity.Fields.coUnidadeNotificacao);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DT_SIN_PRI, NotificationEntity.Fields.dtDiagnosticoSintoma);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(SEM_PRI, NotificationEntity.Fields.dsSemanaSintoma);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NM_PACIENT, NotificationEntity.Fields.noNomePaciente);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DT_NASC, NotificationEntity.Fields.dtNascimento);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NU_IDADE_N, NotificationEntity.Fields.nuIdade);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(CS_SEXO, NotificationEntity.Fields.tpSexo);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(CS_GESTANT, NotificationEntity.Fields.tpGestante);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(CS_RACA, NotificationEntity.Fields.tpRacaCor);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(CS_ESCOL_N, NotificationEntity.Fields.tpEscolaridade);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ID_CNS_SUS, NotificationEntity.Fields.nuCartaoSus);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NM_MAE_PAC, NotificationEntity.Fields.noNomeMae);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(SG_UF, NotificationEntity.Fields.coUfResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ID_MN_RESI, NotificationEntity.Fields.coMunicipioResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ID_DISTRIT, NotificationEntity.Fields.coDistritoResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ID_BAIRRO, NotificationEntity.Fields.coBairroResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NM_BAIRRO, NotificationEntity.Fields.noBairroResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ID_LOGRADO, NotificationEntity.Fields.coLogradouroResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NM_LOGRADO, NotificationEntity.Fields.noLogradouroResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NU_NUMERO, NotificationEntity.Fields.nuResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NM_COMPLEM, NotificationEntity.Fields.dsComplementoResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NU_CEP, NotificationEntity.Fields.nuCepResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NU_DDD_TEL, NotificationEntity.Fields.nuDddResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NU_TELEFON, NotificationEntity.Fields.nuTelefoneResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(CS_ZONA, NotificationEntity.Fields.tpZonaResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ID_PAIS, NotificationEntity.Fields.coPaisResidencia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DT_INVEST, NotificationEntity.Fields.dtInvestigacao);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(CLASSI_FIN, NotificationEntity.Fields.tpClassificacaoFinal);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(CRITERIO, NotificationEntity.Fields.tpCriterioConfirmacao);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(FEBRE, NotificationEntity.Fields.febre);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(MIALGIA, NotificationEntity.Fields.mialgia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(CEFALEIA, NotificationEntity.Fields.cefaleia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(EXANTEMA, NotificationEntity.Fields.exantema);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(VOMITO, NotificationEntity.Fields.vomito);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(NAUSEA, NotificationEntity.Fields.nausea);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DOR_COSTAS, NotificationEntity.Fields.dorCostas);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(CONJUNTVIT, NotificationEntity.Fields.conjuntivite);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ARTRITE, NotificationEntity.Fields.artrite);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ARTRALGIA, NotificationEntity.Fields.artralgia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(PETEQUIA_N, NotificationEntity.Fields.petequia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(LEUCOPENIA, NotificationEntity.Fields.leucopenia);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(LACO, NotificationEntity.Fields.laco);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DOR_RETRO, NotificationEntity.Fields.dorRetro);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DIABETES, NotificationEntity.Fields.diabetes);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(HEMATOLOG, NotificationEntity.Fields.hematologicas);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(HEPATOPAT, NotificationEntity.Fields.hepatopatias);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(RENAL, NotificationEntity.Fields.renal);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(HIPERTENSA, NotificationEntity.Fields.hipertensao);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(ACIDO_PEPT, NotificationEntity.Fields.acidoPeptica);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(AUTO_IMUNE, NotificationEntity.Fields.autoImune);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DT_SORO, NotificationEntity.Fields.dtColetaExame);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(RESUL_SORO, NotificationEntity.Fields.tpResultExame);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DT_NS1, NotificationEntity.Fields.dtColetaNs1);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(RESUL_NS1, NotificationEntity.Fields.tpResultNs1);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DT_VIRAL, NotificationEntity.Fields.dtColetaIsolamento);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(RESUL_VI_N, NotificationEntity.Fields.tpResultIsolamento);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DT_PCR, NotificationEntity.Fields.dtColetaRtpcr);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(RESUL_PCR_, NotificationEntity.Fields.tpResultRtpcr);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(SOROTIPO, NotificationEntity.Fields.tpSorotipo);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(EVOLUCAO, NotificationEntity.Fields.tpEvolucaoCaso);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DT_OBITO, NotificationEntity.Fields.dtObito);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DT_ENCERRA, NotificationEntity.Fields.dtEncerramento);
        NOTIFICATION_DBF_FIELD_TO_ENTITY_FIELD.put(DS_OBS, NotificationEntity.Fields.dsObservacao);
    }
}
