seta:
    logging:
        runnable: true
    notification:
        runnable:
            chunk-size: 5
    webclients:
        geocoding-api:
            url: "https://maps.googleapis.com/maps/api/geocode"
            key: ${GEOCODING_API_KEY}
        ibge:
            url: "https://servicodados.ibge.gov.br/api"
spring:
    application:
        name: seta-notification-api
    datasource:
        url: jdbc:postgresql://localhost:5432/seta
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
    data:
        redis:
            url: ${REDIS_URL}
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB
logging:
    level:
        org:
            springframework: